# Generated by Django 4.2.1 on 2023-05-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimettaConnect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300, verbose_name='Адрес сервера')),
                ('username', models.CharField(max_length=300, verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль или токен')),
            ],
        ),
    ]
