# Generated by Django 4.2.1 on 2023-05-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimettaProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jira_tag', models.CharField(max_length=50, verbose_name='Сокращенное имя, из Jira')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование проекта')),
                ('project_id', models.CharField(max_length=300, verbose_name='Наименование проекта')),
                ('task', models.CharField(max_length=300, verbose_name='Задача')),
                ('task_id', models.CharField(max_length=300, verbose_name='ID проекта')),
            ],
        ),
    ]
