# Generated by Django 4.2.1 on 2023-05-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetta', '0002_timettaprojects'),
    ]

    operations = [
        migrations.AddField(
            model_name='timettaconnect',
            name='tokens',
            field=models.JSONField(default=dict, verbose_name='Токены API'),
        ),
    ]
