# Generated by Django 4.2.1 on 2023-05-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetta', '0003_timettaconnect_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='timettaconnect',
            name='projects_list',
            field=models.JSONField(default=dict, verbose_name='Проекты'),
        ),
    ]
