# Generated by Django 4.2.1 on 2023-05-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetta', '0004_timettaconnect_projects_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='timettaconnect',
            name='simple',
            field=models.TextField(default='{{ task }}: {{ task_url }}', verbose_name='Шаблон'),
        ),
    ]
