# Generated by Django 4.2.1 on 2023-05-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetta', '0005_timettaconnect_simple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timettaconnect',
            name='simple',
            field=models.TextField(default='{{ issue }}: {{ issue_link }}', verbose_name='Шаблон'),
        ),
    ]
