# Generated by Django 4.2.2 on 2023-06-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetta', '0006_alter_timettaconnect_simple'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=400, verbose_name='Задание')),
            ],
        ),
        migrations.AddField(
            model_name='timettaprojects',
            name='calendar_summary',
            field=models.ManyToManyField(blank=True, null=True, to='timetta.calendarsummary', verbose_name='Встречи'),
        ),
    ]
