# Generated by Django 4.2.2 on 2023-06-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetta', '0007_calendarsummary_timettaprojects_calendar_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timettaprojects',
            name='calendar_summary',
        ),
        migrations.AddField(
            model_name='timettaprojects',
            name='meeting_summary',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Заголовок митинг'),
        ),
        migrations.AddField(
            model_name='timettaprojects',
            name='meeting_task_id',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Задача митинга'),
        ),
    ]
