# Generated by Django 4.2.2 on 2023-06-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetta', '0008_remove_timettaprojects_calendar_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timettaprojects',
            name='meeting_template',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Сообщение в тиметте'),
        ),
    ]
