# Generated by Django 4.2.2 on 2023-06-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetta', '0011_remove_timettaconnect_projects_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timettaconnect',
            name='projects_list',
            field=models.JSONField(default=dict, verbose_name='Проекты'),
        ),
    ]
