# Generated by Django 4.2.2 on 2023-06-15 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetta', '0012_timettaconnect_projects_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timettaconnect',
            name='projects_list',
        ),
    ]
