# Generated by Django 4.2.1 on 2023-05-22 13:28

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JiraFilters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Имя')),
                ('jsql', models.CharField(max_length=500, verbose_name='Запрос')),
            ],
        ),
        migrations.CreateModel(
            name='JitaConnect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300, verbose_name='Адрес сервера')),
                ('username', models.CharField(max_length=300, verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль или токен')),
            ],
        ),
        migrations.CreateModel(
            name='JiraExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(default=False)),
                ('day_of_week', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Cуббота'), (7, 'Воскресенье')], default=5, max_length=7, verbose_name='Время запуска')),
                ('type', models.CharField(choices=[('daily', 'Ежедневно'), ('monthly', 'Раз в неделю')], default='monthly', max_length=10, verbose_name='Тип')),
                ('time', models.CharField(max_length=5, verbose_name='Время запуска')),
                ('filter', models.ManyToManyField(null=True, to='Jira.jirafilters', verbose_name='Фильтр')),
            ],
        ),
    ]
