# Generated by Django 4.2.1 on 2023-05-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jira', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiraexercise',
            name='type',
            field=models.CharField(choices=[('monthly', 'Раз в неделю'), ('daily', 'Ежедневно')], default='monthly', max_length=10, verbose_name='Тип'),
        ),
    ]
