# Generated by Django 4.2.1 on 2023-06-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jira', '0002_alter_jiraexercise_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraexercise',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='jiraexercise',
            name='type',
            field=models.CharField(choices=[('daily', 'Ежедневно'), ('monthly', 'Раз в неделю')], default='monthly', max_length=10, verbose_name='Тип'),
        ),
    ]
