# Generated by Django 4.2.1 on 2023-06-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jira', '0003_jiraexercise_name_alter_jiraexercise_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiraexercise',
            name='time',
            field=models.CharField(default='23:00', max_length=5, verbose_name='Время запуска'),
        ),
        migrations.AlterField(
            model_name='jiraexercise',
            name='type',
            field=models.CharField(choices=[('monthly', 'Раз в неделю'), ('daily', 'Ежедневно')], default='monthly', max_length=10, verbose_name='Тип'),
        ),
    ]
