# Generated by Django 4.2.2 on 2023-07-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jira', '0005_alter_jiraexercise_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiraexercise',
            name='type',
            field=models.CharField(choices=[('monthly', 'Раз в неделю'), ('daily', 'Ежедневно')], default='monthly', max_length=10, verbose_name='Тип'),
        ),
    ]
