# Generated by Django 4.2.1 on 2023-06-04 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_filter_custom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='filter',
            new_name='user_filter',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='filter_custom',
            new_name='user_filter_custom',
        ),
    ]
