# Generated by Django 4.2.1 on 2023-06-04 21:41

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_filter_customuser_user_filter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='synchronization_day_of_week',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Cуббота'), (7, 'Воскресенье')], default=7, max_length=7, verbose_name='День запуска'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='time',
            field=models.CharField(default='23:00', max_length=5, verbose_name='Время запуска'),
        ),
    ]
