# Generated by Django 4.2.2 on 2023-06-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_time_customuser_user_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='synchronization_meetings',
            field=models.BooleanField(default=False),
        ),
    ]
