# Generated by Django 4.2.2 on 2023-06-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_synchronization_meetings'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='synchronization_meetings_key',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Токен доступа к Я.Календарю'),
        ),
    ]
