# Generated by Django 4.2.2 on 2023-07-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_synchronization_meetings_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notification',
            field=models.CharField(default='disable', max_length=50, verbose_name='Уведомление'),
        ),
    ]
